version: "3.9"
volumes:
  mosquitto_conf:
  mosquitto_data:
  mosquitto_log:
  config_influxdb:
  data_influxdb:
  grafana-storage:

services:
  mosquitto:
    image: eclipse-mosquitto:2.0
    ports:
      - "1883:1883"
    volumes:
      - mosquitto_conf:/mosquitto/config
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log

  influxdb:
    image: "influxdb:2.2.0-alpine"
    ports: 
      - "8086:8086"
    volumes:
      - data_influxdb:/var/lib/influxdb2
      - config_influxdb:/etc/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=admin1234
      - DOCKER_INFLUXDB_INIT_ORG=udc
      - DOCKER_INFLUXDB_INIT_BUCKET=consumo_agua
      - DOCKER_INFLUXDB_INIT_RETENTION=1w
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=consumo-agua-token
  
  telegraf:
    image: telegraf:1.22.4
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 20
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf
  
  nodered:
    image: nodered/node-red:3.1-debian
    ports:
      - "1880:1880"
    volumes:
      - ./data:/data
    restart: unless-stopped